spring:
  application:
    name: ApiGateway
  server:
    port: 8080
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
          filters:
            - name: AuthFilter

        - id: habitaciones
          uri: http://localhost:8082
          predicates:
            - Path=/habitaciones/**
          filters:
            - name: AuthFilter

        - id: seguridad
          predicates:
            - Path=/auth/**
          uri: ${AUTH_ROUTE_URI:http://localhost:8090}
        # - id: internal
        #  uri: http://localhost:8080
        #   predicates:
        #     - Path=/process/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    root: debug
    sun: error
    javax: error